### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by SCCCR** [ZHENFENG13/My-Blog#110]
在md里直接 paste图片，显示上传失败。
环境：本地部署和服务器端部署错误相同。
问题定位：UploadController里，文件的 directory 没有创建出来，如下：
```java
if (!fileDirectory.exists()) {
    if (!fileDirectory.mkdir()) {  // 文件没创建出来
        throw new IOException("文件夹创建失败,路径为：" + fileDirectory);
    }
}
```
这里直接抛异常出去了，我找了很久没找到是什么原因导致这个文件夹无法创建，知道怎么回事的同学可否提示一下。

**Comment by ZHENFENG13** [comment]
异常信息贴一下，可能是路径写错了。

**Comment by SCCCR** [comment]
> 异常信息贴一下，可能是路径写错了。


异常信息：

```java
java.io.IOException: 文件夹创建失败,路径为：\opt\deploy\upload
	at com.site.blog.my.core.controller.admin.UploadController.upload(UploadController.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:142)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
...............

```

Constants.java 里的路径
```java
package com.site.blog.my.core.config;

/**
 * Created by 13 on 2019/5/24.
 */
public class Constants {
    public final static String FILE_UPLOAD_DIC = "/opt/deploy/upload/";//上传文件的默认url前缀，根据部署设置自行修改
}

```

**Comment by ZHENFENG13** [comment]
那你现在服务器上有这些路径吗？`/opt/deploy/upload/`

**Comment by SCCCR** [comment]
啊这，是要自己创建的吗？我去试试。
我一直以为这个 mkdir会自动给创建出来

**Comment by SCCCR** [comment]
在服务器创建了文件夹以后是可以上传图片了，我想知道这个是为什么？

难道是服务器端的权限问题么？
